### ISSUE TITLE
deploy_db function expects "probability" output column for classification models

### ISSUE THREAD

**Issue by ZachC16** [splicemachine/pysplice#69]
When deploying Pyspark classification models to a database, deploy_db expects the output column of the model to be "probability", but this is not the case for the Linear Support Vector Machine model (https://spark.apache.org/docs/2.4.0/ml-classification-regression.html#linear-support-vector-machine), resulting in an error.

To reproduce, build this type of model and save it to the Splice Machine DB. Then, use deploy_db to deploy the model to a database (I created a new table). Attempting to add values to the table will throw the exception.  

Stack trace:

`Py4JJavaError: An error occurred while calling o5977.execute.
: java.sql.SQLException: Splice Engine exception: unexpected exception
	at com.splicemachine.db.client.am.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:105)
	at com.splicemachine.db.client.am.SqlException.getSQLException(SqlException.java:368)
	at com.splicemachine.db.client.am.Statement.execute(Statement.java:915)
	at com.splicemachine.spark.splicemachine.SplicemachineContext.execute(SplicemachineContext.scala:318)
	at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.splicemachine.db.client.am.SqlException: Splice Engine exception: unexpected exception
	at com.splicemachine.db.client.am.Statement.completeSqlca(Statement.java:1858)
	at com.splicemachine.db.client.am.Statement.completeExecuteImmediate(Statement.java:1443)
	at com.splicemachine.db.client.net.NetStatementReply.parseEXCSQLIMMreply(NetStatementReply.java:210)
	at com.splicemachine.db.client.net.NetStatementReply.readExecuteImmediate(NetStatementReply.java:61)
	at com.splicemachine.db.client.net.StatementReply.readExecuteImmediate(StatementReply.java:49)
	at com.splicemachine.db.client.net.NetStatement.readExecuteImmediate_(NetStatement.java:128)
	at com.splicemachine.db.client.am.Statement.readExecuteImmediate(Statement.java:1439)
	at com.splicemachine.db.client.am.Statement.flowExecute(Statement.java:2167)
	at com.splicemachine.db.client.am.Statement.executeX(Statement.java:920)
	at com.splicemachine.db.client.am.Statement.execute(Statement.java:906)
	... 11 more
Caused by: com.splicemachine.db.client.am.SqlException: Java exception: 'java.lang.IllegalArgumentException: invalid fields: probability: java.io.IOException'.
	... 21 more
Caused by: com.splicemachine.db.client.am.SqlException: Java exception: 'invalid fields: probability: java.lang.IllegalArgumentException'.
	... 21 more
`

**Comment by Ben-Epstein** [comment]
Fixed in https://github.com/splicemachine/pysplice/pull/78
